### ISSUE TITLE
Django items

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/dnanexus#8]
When starting the app I get this notification: 
`You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.`

When trying to use the `admin` URL  I get the following: 
"A server error occurred.  Please contact the administrator." in the browser and in the terminal:
```
File "/usr/local/lib/python3.8/dist-packages/backports/zoneinfo/_common.py", line 27, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
backports.zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'
```

**Comment by cdgriffin2001** [comment]
The error message you encountered is related to a missing time zone entry for 'UTC' in the backports zoneinfo library. This issue often occurs when using Python 3.8 or earlier versions that lack the built-in time zone database.

To fix the problem, you can follow these steps:

Upgrade Python: If possible, upgrade your Python version to 3.9 or later, as these versions include the necessary time zone database by default.

Use a Time Zone Library: If upgrading Python is not an option, you can use a separate time zone library, such as 'pytz,' to provide the necessary time zone data. Install the 'pytz' library using pip:

bash:
pip install pytz
or (pip3 install pytz)

Update Django Settings: Once 'pytz' is installed, you need to update your Django settings to use it. Open the "settings.py" file in your project and add the following line:

TIME_ZONE = 'UTC'

Apply Migrations: After making these changes, apply the pending migrations by running:

python manage.py migrate
(or python3)

Run the Server: Start the development server again:

python manage.py runserver
or (python3)

The missing 'UTC' time zone issue should be resolved now, and you should be able to use the admin URL without any errors.

Additionally, it's important to apply the pending migrations (e.g., for 'admin,' 'auth,' 'contenttypes,' and 'sessions') to ensure that the necessary database tables and configurations are set up correctly. The 'python or(python3) manage.py migrate' command handles this process for you.

**Comment by HadleyKing** [comment]
fixed with `bconexus_uat_v1.5_081523`
